### ISSUE TITLE
Configuration in Online Examination

### ISSUE THREAD

**Issue by tgsiva** [tgsiva/Online-Examination#2]
- [x] Test connectivity flow between admin, controller & user

**Comment by rajapandi** [comment]
connectivity flow between admin, controller & user has finished now

**Comment by rajapandi** [comment]
1.  i need to correct exam date ant time and publishing.
2. i need to compare face recognition.
3. i need to install biometric  driver  fingerprint

**Comment by tgsiva** [comment]
Okay done
